# Config for transformer_big en->ja with BT and politeness tagged data.
seed: 1905
# Data
save_data: models/transformer_big/en-ja-bt-pofo-0001
src_vocab: models/transformer_big/en-ja-bt-pofo-0001.vocab.src
tgt_vocab: models/transformer_big/en-ja-bt-pofo-0001.vocab.tgt
overwrite: True
data:
      corpus_big:
            path_src: data/train/preprocessed/wmt2021-bitext-pofo-tagged.en
            path_tgt: data/train/preprocessed/wmt2021-bitext.ja
            transforms: [sentencepiece, filtertoolong]
      backtranslation:
            path_src: data/wmt2021/mono/4M_subset.en
            path_tgt: data/wmt2021/mono/4M_filtered_postprocessed.ja
            src_prefix: BACKTRANSLATION
            tgt_prefix: BACKTRANSLATION
            transforms: [filtertoolong, sentencepiece, prefix]
      valid:
            path_src: data/dev/preprocessed/newsdev2020-enja.en
            path_tgt: data/dev/preprocessed/newsdev2020-enja.ja
            transforms: [sentencepiece, filtertoolong]
# General settings
skip_empty_level: silent
save_model: models/transformer_big/en-ja-bt-pofo-0001
src_subword_model: sentencepiece/transformer_big.en.model
tgt_subword_model: sentencepiece/transformer_big.ja.model
src_subword_type: sentencepiece
tgt_subword_type: sentencepiece

#filter long sentences
src_seq_length: 100
tgt_seq_length: 100

# General opts
save_checkpoint_steps: 10000
valid_steps: 10000
train_steps: 1000000
report_every: 100


# Batching
queue_size: 10000
bucket_size: 32768
world_size: 1
gpu_ranks: [0]
batch_type: "tokens"
batch_size: 2500   # Using 3000 caused OOM error in the past.
valid_batch_size: 8
max_generator_batches: 2
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 0.001
warmup_steps: 16000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 16
rnn_size: 1024
word_vec_size: 1024
transformer_ff: 4096
dropout_steps: [0]
dropout: [0.3]
attention_dropout: [0.1]
early_stopping: 3

# Visualization
log_file: logfiles/en-ja-bt-pofo-0001
tensorboard: true
tensorboard_log_dir: logs
