# Config for transformer_big ja->en.
seed: 1111
# Data
save_data: models/transformer_big/ja-en
src_vocab: models/transformer_big/ja-en.vocab.src
tgt_vocab: models/transformer_big/ja-en.vocab.tgt
overwrite: False
data:
      corpus_big:
            path_src: /nas/models/experiment/ja-en/wmt2021/data/train/preprocessed/wmt2021-bitext.ja
            path_tgt: /nas/models/experiment/ja-en/wmt2021/data/train/preprocessed/wmt2021-bitext.en
            transforms: [filtertoolong]
      valid:
            path_src:  /nas/models/experiment/ja-en/wmt2021/data/dev/preprocessed/newsdev2020-jaen-src.ja
            path_tgt:  /nas/models/experiment/ja-en/wmt2021/data/dev/preprocessed/newsdev2020-jaen-ref.en
            transforms: [filtertoolong]
# General settings
skip_empty_level: silent
save_model: /nas/models/experiment/ja-en/wmt2021/models/transformer_big/ja-en/
src_subword_model: /nas/models/experiment/ja-en/wmt2021/sentencepiece/transformer_base.ja.model
tgt_subword_model: /nas/models/experiment/ja-en/wmt2021/sentencepiece/transformer_base.en.model
src_subword_type: sentencepiece
tgt_subword_type: sentencepiece

#filter long sentences
src_seq_length: 100
tgt_seq_length: 100

# General opts
save_checkpoint_steps: 10000
valid_steps: 10000
train_steps: 300000
report_every: 100


# Batching
queue_size: 10000
bucket_size: 32768
world_size: 2
gpu_ranks: [0,1]
batch_type: "tokens"
batch_size: 2500   # Using 3000 caused OOM error in the past.
valid_batch_size: 8
max_generator_batches: 2
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 0.2
warmup_steps: 16000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 16
rnn_size: 1024
word_vec_size: 1024
transformer_ff: 4096
dropout_steps: [0]
dropout: [0.3]
attention_dropout: [0.1]
early_stopping: 5

# Visualization
tensorboard: true
tensorboard_log_dir: /nas/models/experiment/ja-en/wmt2021/logs
